name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - matplotlib=3.8.2
  - pandas=1.4.4
  - pip=23.3.1
  - scikit-learn=1.3.2
  - jupyterlab=4.1.3
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
      - databricks_cli==0.8.7
      - hydra-core=1.3.2