name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pandas=2.1.3
  - pytest=8.3.4  # Updated to a more recent version
  - scipy=1.10.1  # Ensure compatibility with Python 3.10 and pandas
  - pip=23.3.1
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
