name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - hydra-core=1.3.2
  - matplotlib=3.8.2
  - pandas=2.1.3
  - requests=2.28
  - pyyaml
  - jupyterlab=4.1.3
  - pip=23.3.1
  - scikit-learn=1.5.2
  - pyarrow
  - pytest=8.3.4
  - scipy=1.12.1
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
      - databricks-cli==0.18.0