name: mlflow_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - hydra-core=1.3.2
  - matplotlib
  - scikit-learn
  - pip
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
