name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - hydra-core=1.3.2
  - mlflow=2.8.1
  - pandas=2.1.3
  - jupyterlab=4.0.9
  - pytest=8.3.4
  - matplotlib=3.8.2
  - pip=23.3.1
  - pip:
      - wandb==0.19.2
      - databricks-cli==0.18.0
