main:
  project_name: "nyc_airbnb"
  experiment_name: "pipeline_execution"
  components_repository: "https://github.com/jand769/Project-Build-an-ML-Pipeline-Starter.git"
  steps: "all"

etl:
  sample: "sample2.csv"
  min_price: 10
  max_price: 350

basic_cleaning:
  input_artifact: "sample2.csv:latest"
  output_artifact: "clean_sample2.csv"
  output_type: "clean_data"
  output_description: "Cleaned dataset for sample2.csv"

data_check:
  kl_threshold: 0.1

modeling:
  test_size: 0.2
  random_seed: 42
  stratify_by: "neighbourhood_group"
  max_tfidf_features: 10
  random_forest:
    n_estimators: 200
    max_depth: 10
    min_samples_split: 2
    min_samples_leaf: 1
