main:
  components_repository: "https://github.com/udacity/Project-Build-an-ML-Pipeline-Starter.git#components"
  project_name: nyc_airbnb
  experiment_name: development
  steps: all

etl:
  sample: "sample1.csv"
  min_price: 10
  max_price: 350

basic_cleaning:
  input_artifact: "sample1.csv:latest"
  output_artifact: "clean_sample1.csv"
  output_type: "cleaned_data"
  output_description: "Data cleaned for outliers and inconsistencies"

data_check:
  input_artifact: clean_sample1.csv:latest
  reference_artifact: clean_sample1.csv:reference
  kl_threshold: 0.2
  min_price: 10
  max_price: 350

modeling:
  test_size: 0.2
  random_seed: 42
  stratify_by: neighbourhood_group
  random_forest:
    max_depth: 10
    n_estimators: 100
