main:
  steps: "download,basic_cleaning"

etl:
  sample_artifact: "sample.csv"
  artifact_name: "raw_data.csv"
  artifact_type: "raw_data"
  artifact_description: "Raw data as downloaded"

basic_cleaning:
  input_artifact: "sample.csv:latest"
  output_artifact: "clean_sample.csv"
  output_type: "clean_sample"
  output_description: "Cleaned Airbnb data"
  min_price: 10
  max_price: 350
