main:
  components_repository: "https://github.com/udacity/Project-Build-an-ML-Pipeline-Starter.git#components"
  project_name: nyc_airbnb
  experiment_name: development
  steps: all

etl:
  sample: "sample1.csv"
  min_price: 10
  max_price: 350

basic_cleaning:
  input_artifact: "sample1.csv:latest"
  max_price: 350
  min_price: 10
  output_artifact: "clean_sample1.csv"
  output_description: "Data cleaned for outliers and inconsistencies"
  output_type: "cleaned_data"


data_check:
  kl_threshold: 0.1

data_split:
  input_artifact: "clean_sample1.csv:latest"

modeling:
  trainval_artifact: "trainval_data.csv:latest"
  test_size: 0.3
  val_size: 0.2
  random_seed: 42
  stratify_by: "neighborhood_group"
  rf_config: "random_forest_config.json"
  max_tfidf_features: 10
  output_artifact: "random_forest_model"