main:
  components_repository: "https://github.com/udacity/Project-Build-an-ML-Pipeline-Starter.git#components"
  steps: "all"

etl:
  sample: "sample2.csv"
  min_price: 10
  max_price: 350

basic_cleaning:
  input_artifact: "sample2.csv:latest"
  output_artifact: "clean_sample2.csv"
  output_type: "clean_sample"
  output_description: "Data with outliers and null values removed"

data_check:
  kl_threshold: 0.1

modeling:
  test_size: 0.33
  random_seed: 42
  stratify_by: "neighbourhood_group"
  max_tfidf_features: 10
  random_forest:
    n_estimators: 100
    max_depth: 10
    random_state: 42
