main:
  components_repository: "https://github.com/udacity/Project-Build-an-ML-Pipeline-Starter.git#components"
  project_name: nyc_airbnb
  experiment_name: development
  steps: all

etl:
  sample: "sample1.csv"  # Updated to sample1.csv
  min_price: 10
  max_price: 350

basic_cleaning:
  input_artifact: "sample1.csv:latest"  # Updated to sample1.csv
  output_artifact: "clean_sample1.csv"  # Updated to clean_sample1.csv
  output_type: "cleaned_data"
  output_description: "Data cleaned for outliers and inconsistencies"
