main:
  components_repository: "https://github.com/udacity/Project-Build-an-ML-Pipeline-Starter.git#components"
  project_name: nyc_airbnb
  experiment_name: development
  steps: all

etl:
  sample: "sample2.csv"
  min_price: 10
  max_price: 350

basic_cleaning:
  input_artifact: "sample2.csv:latest"
  output_artifact: "clean_sample2.csv"
  output_type: "clean_sample"
  output_description: "Dataset cleaned of outliers and invalid geolocations"

data_check:
  input_artifact: "clean_sample2.csv:latest"
  reference_artifact: "clean_sample.csv:reference"
  kl_threshold: 0.2
  min_price: 10
  max_price: 350

modeling:
  test_size: 0.2
  val_size: 0.2
  random_seed: 42
  stratify_by: "neighbourhood_group"
  max_tfidf_features: 5
  random_forest:
    n_estimators: 200
    max_depth: 50
    min_samples_split: 4
    min_samples_leaf: 3
    n_jobs: -1
    criterion: squared_error
    max_features: 0.5
    oob_score: true

test_model:
  mlflow_model: "random_forest_export:prod"
  test_data: "test_data.csv:latest"
