main:
  components_repository: "https://github.com/udacity/Project-Build-an-ML-Pipeline-Starter.git#components"
  project_name: nyc_airbnb
  experiment_name: development
  steps: all

etl:
  sample: "sample1.csv"
  min_price: 10  # dollars
  max_price: 350  # dollars

data_check:
  kl_threshold: 0.2
  ref: "clean_sample1.csv:reference"  # Ensure this matches the W&B artifact
