main:
  components_repository: "https://github.com/udacity/Project-Build-an-ML-Pipeline-Starter.git#components"
  project_name: nyc_airbnb
  experiment_name: development
  steps: all

etl:
  sample: sample1.csv  # Default dataset

basic_cleaning:
  input_artifact: sample1.csv:latest
  max_price: 350
  min_price: 10
  output_artifact: clean_sample1.csv
  output_description: "Cleaned sample1 Airbnb data"
  output_type: csv


train_val_test_split:
  test_size: 0.2
  random_state: 42
  stratify: true  # Stratify by 'neighbourhood_group'

train_random_forest:
  max_depth: 10
  max_tfidf_features: 10
  min_samples_leaf: 1
  min_samples_split: 2
  n_estimators: 200
  n_jobs: -1
  random_seed: 42
  output_artifact: random_forest_export
  output_type: model
  output_description: "Trained Random Forest model"

test_regression_model:
  test_artifact: test_data.csv:latest
  mlflow_model: random_forest_export:prod
  output_artifact: test_model
  output_type: test_result
  output_description: "Results from testing the production-ready model"
