name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - hydra-core=1.3.2
  - pandas=2.1.3
  - matplotlib=3.8.2
  - scikit-learn=1.3.2
  - pytest>=7.0.0
  - scipy>=1.7
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
