name: train_random_forest
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.0
  - pandas=2.1.3
  - pytest>=7.0.0
  - scipy>=1.13.1
  - pip=23.3.1
  - pyyaml=5.3.1
  - pip:
      - mlflow==2.8.1
      - wandb==0.16.0
      - databricks-cli==0.18.0
      - hydra-core==1.3.2